version: '3'

services:
  tomcat:
    build: ./
    image: own_tomcat:1.0
    ports:
      - 8085:8080
    volumes:
      - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./webapps:/usr/local/tomcat/webapps